"""baseline inicial sisventas

Revision ID: 0ee0269662e8
Revises: 
Create Date: 2026-05-29 16:16:30.563960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee0269662e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_history_empresa_id'), 'admin_history', ['empresa_id'], unique=False)
    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('system_expected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_amount_counted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_empresa_id'), 'cash_sessions', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_status'), 'cash_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_cash_sessions_user_id'), 'cash_sessions', ['user_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_doc', sa.String(length=10), nullable=False),
    sa.Column('num_doc', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=160), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'num_doc', name='uq_clientes_empresa_num_doc')
    )
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_index('ix_clientes_empresa_num_doc', 'clientes', ['empresa_id', 'num_doc'], unique=False)
    op.create_index('ix_clientes_empresa_razon', 'clientes', ['empresa_id', 'razon_social'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('web', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_index(op.f('ix_super_admins_username'), 'super_admins', ['username'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_empresa_id'), 'categorias', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_usuario_empresa_email'),
    sa.UniqueConstraint('empresa_id', 'username', name='uq_usuario_empresa_username')
    )
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_reset_token'), 'usuarios', ['reset_token'], unique=False)
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recurso', sa.String(length=60), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_empresa_id'), 'access_requests', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_access_requests_user_id'), 'access_requests', ['user_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('unidad', sa.String(length=10), server_default='UND', nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_empresa_id'), 'productos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cash_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('efectivo_recibido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vuelto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=2), server_default='B', nullable=False),
    sa.Column('serie', sa.String(length=4), server_default='B001', nullable=False),
    sa.Column('correlativo', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_empresa_id'), 'ventas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ventas_fecha'), 'ventas', ['fecha'], unique=False)
    op.create_index(op.f('ix_ventas_usuario_id'), 'ventas', ['usuario_id'], unique=False)
    op.create_table('inventario_movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_movimientos_empresa_id'), 'inventario_movimientos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_inventario_movimientos_producto_id'), 'inventario_movimientos', ['producto_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ref_tipo', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_empresa_id'), 'stock_movements', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_producto_id'), 'stock_movements', ['producto_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_tipo'), 'stock_movements', ['tipo'], unique=False)
    op.create_table('venta_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_detalle_producto_id'), 'venta_detalle', ['producto_id'], unique=False)
    op.create_index(op.f('ix_venta_detalle_venta_id'), 'venta_detalle', ['venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_detalle_venta_id'), table_name='venta_detalle')
    op.drop_index(op.f('ix_venta_detalle_producto_id'), table_name='venta_detalle')
    op.drop_table('venta_detalle')
    op.drop_index(op.f('ix_stock_movements_tipo'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_producto_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_empresa_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_inventario_movimientos_producto_id'), table_name='inventario_movimientos')
    op.drop_index(op.f('ix_inventario_movimientos_empresa_id'), table_name='inventario_movimientos')
    op.drop_table('inventario_movimientos')
    op.drop_index(op.f('ix_ventas_usuario_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_empresa_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_empresa_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_access_requests_user_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_empresa_id'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_usuarios_reset_token'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_categorias_empresa_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_super_admins_username'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_table('empresas')
    op.drop_index('ix_clientes_empresa_razon', table_name='clientes')
    op.drop_index('ix_clientes_empresa_num_doc', table_name='clientes')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_cash_sessions_user_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_status'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_empresa_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    op.drop_index(op.f('ix_admin_history_empresa_id'), table_name='admin_history')
    op.drop_table('admin_history')
    # ### end Alembic commands ###
