"""add cash_sessions and stock_movements tables

Revision ID: a0678fd19301
Revises: ef32506d8e01
Create Date: 2026-01-25 18:15:01.416588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0678fd19301'
down_revision: Union[str, Sequence[str], None] = 'ef32506d8e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('system_expected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_amount_counted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_empresa_id'), 'cash_sessions', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_status'), 'cash_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_cash_sessions_user_id'), 'cash_sessions', ['user_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ref_tipo', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_empresa_id'), 'stock_movements', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_producto_id'), 'stock_movements', ['producto_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_tipo'), 'stock_movements', ['tipo'], unique=False)
    op.drop_index(op.f('ix_logs_auditoria_accion'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_empresa_id'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_entidad'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_usuario_id'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    op.drop_constraint(op.f('access_requests_resolved_by_user_id_fkey'), 'access_requests', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('access_requests_resolved_by_user_id_fkey'), 'access_requests', 'usuarios', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_table('logs_auditoria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entidad', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('entidad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('logs_auditoria_empresa_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('logs_auditoria_usuario_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_auditoria_pkey'))
    )
    op.create_index(op.f('ix_logs_auditoria_usuario_id'), 'logs_auditoria', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_entidad'), 'logs_auditoria', ['entidad'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_empresa_id'), 'logs_auditoria', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_accion'), 'logs_auditoria', ['accion'], unique=False)
    op.drop_index(op.f('ix_stock_movements_tipo'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_producto_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_empresa_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_cash_sessions_user_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_status'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_empresa_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    # ### end Alembic commands ###
