"""add empresa ruc direccion telefono web

Revision ID: a546e98fcd55
Revises: 08dececb03e4
Create Date: 2026-01-31 16:51:17.519102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a546e98fcd55'
down_revision: Union[str, Sequence[str], None] = '08dececb03e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('ruc', sa.String(length=11), nullable=True))
    op.add_column('empresas', sa.Column('direccion', sa.String(length=200), nullable=True))
    op.add_column('empresas', sa.Column('telefono', sa.String(length=30), nullable=True))
    op.add_column('empresas', sa.Column('web', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'web')
    op.drop_column('empresas', 'telefono')
    op.drop_column('empresas', 'direccion')
    op.drop_column('empresas', 'ruc')
    # ### end Alembic commands ###
