"""add efectivo_recibido and vuelto to ventas

Revision ID: cecbcbb17454
Revises: 24cb9177fcd2
Create Date: 2026-02-10 21:51:34.854681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecbcbb17454'
down_revision: Union[str, Sequence[str], None] = '24cb9177fcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) Agregar con default para que no rompa filas existentes
    op.add_column(
        "ventas",
        sa.Column("efectivo_recibido", sa.Numeric(12, 2), nullable=True, server_default="0")
    )
    op.add_column(
        "ventas",
        sa.Column("vuelto", sa.Numeric(12, 2), nullable=True, server_default="0")
    )

    # 2) Rellenar datos existentes (por si acaso)
    op.execute("UPDATE ventas SET efectivo_recibido = 0 WHERE efectivo_recibido IS NULL;")
    op.execute("UPDATE ventas SET vuelto = 0 WHERE vuelto IS NULL;")

    # 3) Volverlas NOT NULL
    op.alter_column("ventas", "efectivo_recibido", nullable=False)
    op.alter_column("ventas", "vuelto", nullable=False)

    # (opcional) si NO quieres que quede default permanente a nivel DB:
    op.alter_column("ventas", "efectivo_recibido", server_default=None)
    op.alter_column("ventas", "vuelto", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'vuelto')
    op.drop_column('ventas', 'efectivo_recibido')
    # ### end Alembic commands ###
