"""add cliente_id to ventas

Revision ID: 08dececb03e4
Revises: 301b3b74e82e
Create Date: 2026-01-26 00:30:22.240073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08dececb03e4'
down_revision: Union[str, Sequence[str], None] = '301b3b74e82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ventas', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.drop_column('ventas', 'cliente_id')
    # ### end Alembic commands ###
