"""add user fields + logs auditoria

Revision ID: 147cb71ee801
Revises: 218dfdd3ca24
Create Date: 2026-01-16 13:01:20.599226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '147cb71ee801'
down_revision: Union[str, Sequence[str], None] = '218dfdd3ca24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_accion'), 'logs_auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_empresa_id'), 'logs_auditoria', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_entidad'), 'logs_auditoria', ['entidad'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_usuario_id'), 'logs_auditoria', ['usuario_id'], unique=False)
    op.add_column('usuarios', sa.Column('apellido', sa.String(length=120), nullable=True))
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_usuario_empresa_email', 'usuarios', ['empresa_id', 'email'])
    op.drop_constraint(op.f('usuarios_empresa_id_fkey'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_empresa_id_fkey'), 'usuarios', 'empresas', ['empresa_id'], ['id'])
    op.drop_constraint('uq_usuario_empresa_email', 'usuarios', type_='unique')
    op.drop_column('usuarios', 'last_login_at')
    op.drop_column('usuarios', 'telefono')
    op.drop_column('usuarios', 'apellido')
    op.drop_index(op.f('ix_logs_auditoria_usuario_id'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_entidad'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_empresa_id'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_accion'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
