"""add columns for tables Producto with unidad end marca

Revision ID: 24cb9177fcd2
Revises: a546e98fcd55
Create Date: 2026-01-31 17:47:09.582639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24cb9177fcd2'
down_revision: Union[str, Sequence[str], None] = 'a546e98fcd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('marca', sa.String(length=60), nullable=True))
    op.add_column('productos', sa.Column('unidad', sa.String(length=10), nullable=False, server_default="UND"))
    # ### end Alembic commands ###

    # (Opcional y pro) si no quieres que quede default fijo en BD:
    op.alter_column("productos", "unidad", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'unidad')
    op.drop_column('productos', 'marca')
    # ### end Alembic commands ###
