"""Add and create table clientes

Revision ID: 301b3b74e82e
Revises: 75ce753980e1
Create Date: 2026-01-26 00:18:32.355963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301b3b74e82e'
down_revision: Union[str, Sequence[str], None] = '75ce753980e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_doc', sa.String(length=10), nullable=False),
    sa.Column('num_doc', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=160), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'num_doc', name='uq_clientes_empresa_num_doc')
    )
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_index('ix_clientes_empresa_num_doc', 'clientes', ['empresa_id', 'num_doc'], unique=False)
    op.create_index('ix_clientes_empresa_razon', 'clientes', ['empresa_id', 'razon_social'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clientes_empresa_razon', table_name='clientes')
    op.drop_index('ix_clientes_empresa_num_doc', table_name='clientes')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
