"""add cash_session_id to ventas

Revision ID: 5a885f1050f6
Revises: 35049f7819fc
Create Date: 2026-01-25 18:34:22.009153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a885f1050f6'
down_revision: Union[str, Sequence[str], None] = '35049f7819fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('cash_session_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'cash_session_id')
    # ### end Alembic commands ###
