"""create admin_history

Revision ID: 7f8409eac63c
Revises: a615e4a398fe
Create Date: 2026-01-20 22:52:37.568356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8409eac63c'
down_revision: Union[str, Sequence[str], None] = 'a615e4a398fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_history_empresa_id'), 'admin_history', ['empresa_id'], unique=False)
    op.add_column('access_requests', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.alter_column('access_requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_access_requests_empresa_estado'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_status'), table_name='access_requests')
    op.drop_constraint(op.f('access_requests_empresa_id_fkey'), 'access_requests', type_='foreignkey')
    op.drop_constraint(op.f('access_requests_requested_by_user_id_fkey'), 'access_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_access_requests_approved_by_usuarios'), 'access_requests', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_access_requests_approved_by_usuarios'), 'access_requests', 'usuarios', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('access_requests_requested_by_user_id_fkey'), 'access_requests', 'usuarios', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('access_requests_empresa_id_fkey'), 'access_requests', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_access_requests_status'), 'access_requests', ['status'], unique=False)
    op.create_index(op.f('ix_access_requests_empresa_estado'), 'access_requests', ['empresa_id', 'status'], unique=False)
    op.alter_column('access_requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('access_requests', 'session_id')
    op.drop_index(op.f('ix_admin_history_empresa_id'), table_name='admin_history')
    op.drop_table('admin_history')
    # ### end Alembic commands ###
