"""usuarios: username + recovery + profile

Revision ID: 92b2d54d37b4
Revises: 69fba0a77f54
Create Date: 2026-01-17 16:11:13.021163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b2d54d37b4'
down_revision: Union[str, Sequence[str], None] = '69fba0a77f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('super_admins_email_key'), 'super_admins', type_='unique')
    op.drop_constraint(op.f('uq_super_admins_username'), 'super_admins', type_='unique')
    op.drop_index(op.f('ix_super_admins_username'), table_name='super_admins')
    op.create_index(op.f('ix_super_admins_username'), 'super_admins', ['username'], unique=True)
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.add_column('usuarios', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_usuarios_reset_token'), 'usuarios', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_reset_token'), table_name='usuarios')
    op.drop_column('usuarios', 'reset_token_expires_at')
    op.drop_column('usuarios', 'reset_token')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_username'), table_name='super_admins')
    op.create_index(op.f('ix_super_admins_username'), 'super_admins', ['username'], unique=False)
    op.create_unique_constraint(op.f('uq_super_admins_username'), 'super_admins', ['username'])
    op.create_unique_constraint(op.f('super_admins_email_key'), 'super_admins', ['email'])
    # ### end Alembic commands ###
