"""create access_requests

Revision ID: fda6e4a87e8d
Revises: b5577d6fd959
Create Date: 2026-01-19 18:04:22.344460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda6e4a87e8d'
down_revision: Union[str, Sequence[str], None] = 'b5577d6fd959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_requests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("empresa_id", sa.Integer(), sa.ForeignKey("empresas.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("requested_by_user_id", sa.Integer(), sa.ForeignKey("usuarios.id", ondelete="SET NULL"), nullable=True),
        sa.Column("modulo", sa.String(length=60), nullable=False),  # ej: "dashboard"
        sa.Column("motivo", sa.String(length=255), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=False, server_default="pendiente"),  # pendiente/aprobado/denegado
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", sa.Integer(), sa.ForeignKey("usuarios.id", ondelete="SET NULL"), nullable=True),
    )
    op.create_index("ix_access_requests_empresa_estado", "access_requests", ["empresa_id", "estado"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_access_requests_empresa_estado", table_name="access_requests")
    op.drop_table("access_requests")
